config/routes.rb
Rails.application.routes.draw do

  get "/blog_posts/new" => "blog_posts#new", as: :new_blog_post
  post "blog_posts" => "blog_posts#create", as: :blog_posts
  get "/blog_posts/:id" => "blog_posts#show", as: :blog_post
  get "/blog_posts/:id/edit" => "blog_posts#edit", as: :edit_blog_post
  patch "/blog_posts/:id" => "blog_posts#update"
  delete "blog_posts/:id" => "blog_posts#destroy"

  root "blog_posts#index"

end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController

  def index
    @blog_posts = BlogPost.all
  end 

  def create
    @blog_post = BlogPost.new blog_post_params
    @blog_post.save
    redirect_to root_path
  end
  
  def new
    @blog_post = BlogPost.new 
  end

  def edit
    @blog_post = BlogPost.find params[:id]
  end 

  def update
    @blog_post = BlogPost.find params[:id]
    if @blog_post.update blog_post_params
      redirect_to root_path
    else
      render :edit
    end 
  end 

  def destroy
    @blog_post = BlogPost.find params[:id]
    @blog_post.destroy
    redirect_to root_path
  end 

  private

  def blog_post_params
    params.require(:blog_post).permit(:title, :body, :author)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/views/blog_posts/_form.html.erb
<%= form_for @blog_post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :author %>
  <%= f.text_field :author %> 
  <br>
  <%= f.label :body %>
  <%= f.text_area :body %>
  <br>
  <%= f.submit %>
<% end %>

app/views/blog_posts/edit.html.erb
<h1>Edit page</h1>

<%= render "form" %>

app/views/blog_posts/index.html.erb
<h1>Blog Posts</h1>

<% @blog_posts.each do |blog_post| %>
  <p>Title: <%= blog_post.title %></p>
  <p>Author: <%= blog_post.author %></p>
  <p>Blog Post: <%= blog_post.body %></p>
  <p><%= link_to "Edit", edit_blog_post_path(blog_post) %></p>
  <p><%= link_to "Delete", blog_post_path(blog_post), method: :delete, data: {confirm: "Are you sure?"} %></p>
  <hr>
<% end %>

app/views/blog_posts/new.html.erb
<h1>New Blog Post</h1>

<%= render "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>